[package]
name = "LowkeyRusty"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["errhandlingapi", "handleapi", "winbase", "memoryapi", "synchapi", "tlhelp32", "winerror"] }
